### ISSUE TITLE
unclear how to use this

### ISSUE THREAD

**Issue by raarts** [expo/with-detox-tests#3]
Maybe it's because I have not running an Expo app in production yet, and only tried running from the expo app, but how do I do this?

This repo contains a `bin//Exponent-1.19.0.app` directory, where does that come from? Can I use e2e testing with the Expo app in the iOS emulator?

I hope someone can enlighten me.

**Comment by davidchuyaya** [comment]
Based on this code in [this](https://medium.com/async-la/e2e-testing-react-native-with-detox-screenshots-595146073863#bd2e) Medium article, it looks like you have to copy the app manually while the Expo app is up and running.

By the way, at the time of writing, the newest Expo iOS version is 2.6.7, so you'd want to copy
`~/.expo/ios-simulator-app-cache/Exponent-2.6.7.app`.

**Comment by xcarpentier** [comment]
Hi @davidchuyaya & @raarts,
I'm a contributor of this example project.
Maybe it will be good to copy it by script before e2e test from ~/.expo to ./bin, what do you think?

**Comment by davidchuyaya** [comment]
@xcarpentier That sounds like a good idea.
The path (at least on a Mac) doesn't change unless the version number changes.
Something to note is that you should only need to copy the app once, so maybe do it in some sort of setup script.

**Comment by quinlanj** [comment]
hi all, i've eliminated the manual process of grabbing an `Exponent.app`, and all you need to do is run `./setup.sh` (readme is updated to reflect this change). It should populate your `bin/` with the most recent `Exponent.app`. I'll be closing this issue, but please open another one if you find any problems with the script :)
