### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by nschurmann** [expo/with-detox-tests#7]
Not working at all.

**Comment by quinlanj** [comment]
hi @nschurmann i just updated this project. Please make sure you do the following: 
1. put the latest Exponent.app in `/bin`
2. reset dependencies: `rm -rf node_modules && npm install`

I'll be closing this issue, please open another one if things are still not working for you, and let us know the steps you took and the error/screen you are seeing. This extra info will go a long way into figuring out what went wrong.
